### ISSUE TITLE
Crash when importing project with sends

### ISSUE THREAD

**Issue by git-moss** [bitwig/dawproject#18]
[2021-08-07 13:33:40.357 float-main-app error] Error opening project file C:\Privat\Programming\Bitwig\import-export\Testdateien\Test.dawproject:
	java.io.IOException: java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because "this.UHd" is null
	at com.bitwig.flt.app.wGd.run(SourceFile:237)
	at LO.run(SourceFile:284)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because "this.UHd" is null
	at iQk.m2i(SourceFile:745)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importTrackSettings(SourceFile:275)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.forEachTrack(SourceFile:164)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.convertPhase2(SourceFile:129)
	at com.bitwig.flt.document.api.document.ApiProject.lambda$modifyExcept$2(SourceFile:196)
	at NLc.doProcessEvent(SourceFile:65)
	at NLc.processEvent(SourceFile:53)
	at NLc.processEvent(SourceFile:42)
	at com.bitwig.flt.document.api.document.ApiModificationProcessor.processEvent(SourceFile:37)
	at com.bitwig.flt.document.api.document.ApiModificationProcessor.modify(SourceFile:26)
	at com.bitwig.flt.document.api.document.ApiObject.modify(SourceFile:81)
	at com.bitwig.flt.document.api.document.ApiProject.modifyExcept(SourceFile:193)
	at com.bitwig.flt.document.api.document.ApiProject.importDawProject(SourceFile:180)
	at com.bitwig.extensions.importer.dawproject.DawProjectImporter.CwM(SourceFile:21)
	at com.bitwig.extensions.importer.dawproject.DawProjectImporterDefinition.importProject(SourceFile:56)
	at com.bitwig.flt.app.wGd.run(SourceFile:224)
	... 4 more

**Comment by git-moss** [comment]
This happens when the Send track is tagged with mixerRole="aux" instead of mixerRole="return".

**Comment by git-moss** [comment]
Not sure if this is still the same issue, I replaced in the attached project return-tracks with aux-tracks and it crashes Bitwig completely. Rename .zip to .dawproject:

[Test.zip](https://github.com/bitwig/dawproject/files/7756692/Test.zip)

**Comment by kurasu** [comment]
ok, this one should be fixed in 4.1.3 as well
