### ISSUE TITLE
Crash while exporting .dawproject

### ISSUE THREAD

**Issue by Jurek-Raben** [bitwig/dawproject#26]
So I added ".dawproject" manually in the export dialogue (macos 10.14) and got this crash:

[2021-12-24 10:27:44.655 float-main-app fatal] Application crashing in subsystem GUI Event Thread:
	java.lang.NoSuchFieldError: linear
	at org.glassfish.jaxb.core.v2.model.nav.ReflectionNavigator.getEnumConstants(ReflectionNavigator.java:538)
	at org.glassfish.jaxb.core.v2.model.nav.ReflectionNavigator.getEnumConstants(ReflectionNavigator.java:34)
	at org.glassfish.jaxb.runtime.v2.model.impl.EnumLeafInfoImpl.calcConstants(EnumLeafInfoImpl.java:112)
	at org.glassfish.jaxb.runtime.v2.model.impl.EnumLeafInfoImpl.getConstants(EnumLeafInfoImpl.java:176)
	at org.glassfish.jaxb.runtime.v2.model.impl.EnumLeafInfoImpl.link(EnumLeafInfoImpl.java:183)
	at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.link(ModelBuilder.java:414)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.link(RuntimeModelBuilder.java:96)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:417)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:251)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:77)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1111)
	at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:274)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:263)
	at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:395)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at com.bitwig.dawproject.DawProject.Klb(SourceFile:83)
	at com.bitwig.dawproject.DawProject.Klb(SourceFile:65)
	at com.bitwig.dawproject.DawProject.Klb(SourceFile:144)
	at com.bitwig.extensions.exporter.dawproject.DawProjectExporter.Klb(SourceFile:35)
	at com.bitwig.extensions.exporter.dawproject.DawProjectExporterDefinition.exportProject(SourceFile:16)
	at com.bitwig.flt.app.ttI.KoP(SourceFile:49)
	at ipy.Klb(SourceFile:37)
	at dtC.run(SourceFile:25)
	at cvt.Klb(SourceFile:1063)
	at com.bitwig.flt.app.gCO.Klb(SourceFile:2316)
	at cvt.GTb(SourceFile:1029)
	at cvt.Dl1(SourceFile:983)
	at com.bitwig.flt.app.qbv.Dl1(SourceFile:1913)
	at cvt.WLm(SourceFile:711)
	at com.bitwig.flt.app.BitwigStudioMain.main(SourceFile:201)

**Comment by kurasu** [comment]
This was an obfuscation issue in BWS and is fixed for a future version
