### ISSUE TITLE
Can't export anything from Bitwig Studio 4.0 Beta 2

### ISSUE THREAD

**Issue by zezic** [bitwig/dawproject#3]
Please forgive me, this is probably, not the right place to ask or report anything, but I don't want to bother email support channel with this feature because it is kinda unreleased yet and not mentioned in the changelogs.

So, the issue is literally what the title says. Can't export even an empty project.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector (file:/opt/bitwig-studio/bin/libs.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2021-06-04 02:02:30.470 float-main-app fatal] Application crashing in subsystem GUI Event Thread:
        java.lang.NoSuchFieldError: linear
        at org.glassfish.jaxb.core.v2.model.nav.ReflectionNavigator.getEnumConstants(ReflectionNavigator.java:538)
        at org.glassfish.jaxb.core.v2.model.nav.ReflectionNavigator.getEnumConstants(ReflectionNavigator.java:34)
        at org.glassfish.jaxb.runtime.v2.model.impl.EnumLeafInfoImpl.calcConstants(EnumLeafInfoImpl.java:112)
        at org.glassfish.jaxb.runtime.v2.model.impl.EnumLeafInfoImpl.getConstants(EnumLeafInfoImpl.java:176)
        at org.glassfish.jaxb.runtime.v2.model.impl.EnumLeafInfoImpl.link(EnumLeafInfoImpl.java:183)
        at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.link(ModelBuilder.java:414)
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.link(RuntimeModelBuilder.java:96)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:417)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:251)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:77)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1111)
        at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:140)
        at org.glassfish.jaxb.runtime.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:36)
        at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:358)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
        at Rhj.RdK(SourceFile:83)
        at Rhj.RdK(SourceFile:65)
        at Rhj.RdK(SourceFile:144)
        at RKs.RdK(SourceFile:35)
        at hp.exportProject(SourceFile:16)
        at com.bitwig.flt.app.LJh.Q1M(SourceFile:49)
        at Cdk.RdK(SourceFile:37)
        at cXP.run(SourceFile:25)
        at bZY.RdK(SourceFile:1071)
        at com.bitwig.flt.app.OWd.RdK(SourceFile:2276)
        at bZY.s2E(SourceFile:1037)
        at bZY.gSr(SourceFile:985)
        at com.bitwig.flt.app.s1i.gSr(SourceFile:1922)
        at bZY.mnK(SourceFile:705)
        at com.bitwig.flt.app.BitwigStudioMain.main(SourceFile:198)

Child process with PID 378912 exited with error code: 1
```

**Comment by kurasu** [comment]
Oh, this is the place. 

Think I've fixed now, but only happens in farm-builds so I'll wait for that one to verify it.

**Comment by kurasu** [comment]
Actually was more involved than I though and needed some digging. Something in our packaging processes seem to mess with the JAXB/glassfish way of optimizing reflection access, but that can be disabled with:

System.setProperty("org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.fastBoot","true");

Still waiting for a farm build to validate, but you should be able to do this from within a java debugger already if you're feeling adventurous.

**Comment by kurasu** [comment]
actually forget the feeling adventurous part, there was 2 other fixes needed before this one which are not part of beta 2

**Comment by kurasu** [comment]
Fixed confirmed, will be in Beta 3
