### ISSUE TITLE
 java.util.EmptyStackException

### ISSUE THREAD

**Issue by git-moss** [bitwig/dawproject#31]
[2022-02-23 17:14:27.424 float-main-app error] Error opening project file C:\Users\mos\Desktop\Test.dawproject:
	java.io.IOException: java.util.EmptyStackException
	at com.bitwig.flt.app.Ovr.run(SourceFile:236)
	at GAD.run(SourceFile:284)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.addClipToTimelineOrScene(SourceFile:949)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importAudio(SourceFile:820)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importTimeline(SourceFile:691)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importClip(SourceFile:768)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importClips(SourceFile:745)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importTimeline(SourceFile:675)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importClip(SourceFile:768)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importClips(SourceFile:745)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importTimeline(SourceFile:675)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importLanes(SourceFile:717)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importTimeline(SourceFile:671)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importLanes(SourceFile:717)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importTimeline(SourceFile:671)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.importArrangement(SourceFile:619)
	at com.bitwig.flt.document.api.document.ApiDawProjectImporter.convertPhase2(SourceFile:133)
	at com.bitwig.flt.document.api.document.ApiProject.lambda$modifyExcept$2(SourceFile:196)
	at pt.doProcessEvent(SourceFile:65)
	at pt.processEvent(SourceFile:53)
	at pt.processEvent(SourceFile:42)
	at com.bitwig.flt.document.api.document.ApiModificationProcessor.processEvent(SourceFile:37)
	at com.bitwig.flt.document.api.document.ApiModificationProcessor.modify(SourceFile:26)
	at com.bitwig.flt.document.api.document.ApiObject.modify(SourceFile:68)
	at com.bitwig.flt.document.api.document.ApiProject.modifyExcept(SourceFile:193)
	at com.bitwig.flt.document.api.document.ApiProject.importDawProject(SourceFile:180)
	at com.bitwig.extensions.importer.dawproject.DawProjectImporter.twD(SourceFile:21)
	at com.bitwig.extensions.importer.dawproject.DawProjectImporterDefinition.importProject(SourceFile:56)
	at com.bitwig.flt.app.Ovr.run(SourceFile:223)
	... 4 more

[Test.zip](https://github.com/bitwig/dawproject/files/8125969/Test.zip)

**Comment by git-moss** [comment]
Tested with Bitwig 4.2 Beta 1.

**Comment by kurasu** [comment]
the error messages could be better, but the ids in that file are corrupt, they point in all kinds of directions that doesn't make sense and there are duplicate ids
